name: cliniquette
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.055512449238449335
  lightness: 0.9198530896101147
  saturation: 0.8310969085432589
  rhythmicContrast: 0.7193059904966503
purpose: []
