name: cliniquette
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9398
title: cliniquette - från topp till tå.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101a2b'
    - '#cfbd88'
    - '#606978'
    - '#b0a47b'
    - '#333940'
  brandStrength: 0.6875
  lightness: 0.9198530896101147
  saturation: 0.8310969085432589
  rhythmicContrast: 0.7193059904966503
purpose: []
